# Copyright (C) 2014 paul@marrington.net, see /GPL license

# some support functions generated by coffeescript
window.slice$ = window['__slice'] = [].slice
window['__bind'] = (fn, me) ->
  return -> return fn.apply(me, arguments)
window.bind$ = (obj, key, target) ->
  return -> return (target || obj)[key].apply(obj, arguments)

# Return a named argument from location.search,
# require.opts.name or default
roaster.page_arg = (name, def) ->
  re = new RegExp(name+"=([^&]+)")
  value = re.exec(location.search)
  return value[1] if value?.length is 2
  return roaster.opts[name] if roaster.opts[name]
  return def

# If we specify uSDLC2 instrumentation, load accordingly
if host = roaster.page_arg 'usdlc2-instrumentation'
  require.script host+"/support/usdlc2_browser.js"
  
# so commonJS packages have global and process access
roaster.process = window.process =
    noDeprecation: true
    platform: 'browser'
    env: {}
    nextTick: (action) -> setTimeout action, 10
roaster.global = window

# Loading other modules - finishing with
# project specific initialisation in load=xxx.coffee or js
requirements = ["bootstrap/loaders,common/Sequential"]
scripts = document.getElementsByTagName('script')
script = scripts[scripts.length - 2] # bootstrap, not init
requirements.push loads if loads = script.getAttribute('load')
require requirements..., (imports) ->
  require.css '/client/bootstrap/style.less'
  require.on_ready = (action) -> action()
  action() for action in require.ready